### ISSUE TITLE
Can't install with other nautilus extensions on Ubnutu 20.04

### ISSUE THREAD

**Issue by tiennou44** [costales/folder-color#4]
I used folder-color on Ubnutu 18.04, and it was super :-)
Now on Ubuntu 20.04, there is conflict between python-nautilus and python3-nautilus3 to install them.
In fact, some of nautilus extensions I installed (nautilus-admin, nautilus-nextcloud, ... - I need them) depend on python3-nautilus.
Folder-color depends on python-nautilus.
What solution ?

**Comment by costales** [comment]
Hi,

Honestly, I think is a Nautilus issue, because `folder-color` requires `nautilus-python` and it should get the last, not `python2-nautilus`.

If you don't need the translations, download [this file](https://launchpad.net/~costales/+archive/ubuntu/folder-color/+sourcefiles/folder-color/0.0.88/folder-color_0.0.88.tar.gz).

Extract and then copy as root: `nautilus/nautilus-extension/folder-color.py` into `/usr/share/nautilus-python/extensions/`

Restart Nautilus: `nautilus -q`

And you should have it!

A hug!

**Comment by tiennou44** [comment]
Yes not python2-nautilus but python3-nautilus.
python3-nautilus is, I think, the last version.
Anyway, I'll test folder-color_0.0.88

**Comment by tiennou44** [comment]
That works well.
However, a clean installation in Ubuntu 20.04 with the python3-nautilus version would be highly appreciated.
